### ISSUE TITLE
Station Board requests returns TypeError

### ISSUE THREAD

**Issue by em0lar** [n0emis/pyhafas#6]
StationBoard request with VSN profile returns following error:
```
Traceback (most recent call last):
  File "example.py", line 36, in <module>
    print(vsn.departures(
  File "/home/em0lar/dev/bahn/pyhafas/pyhafas/client.py", line 62, in departures
    return self.profile.parse_station_board_request(res)
  File "/home/em0lar/dev/bahn/pyhafas/pyhafas/profile/base/requests/station_board.py", line 76, in parse_station_board_request
    leg = self.parse_leg(
  File "/home/em0lar/dev/bahn/pyhafas/pyhafas/profile/base/helper/parse_leg.py", line 35, in parse_leg
    common['locL'][departure['locX']]['lid'])
TypeError: 'NoneType' object is not subscriptable
```

In the response it seems like `stopL` is not in the response and therefore `departure` is `None`

**Comment by em0lar** [comment]
This seems not as easy as I thought. Some HaFAS-Versions don't have the required data for the current response type. My plan now is to create a new type like https://github.com/public-transport/hafas-client/blob/master/docs/departures.md for StationBoard
